name: "Log Anomaly Detection"
inputs:
    github-token:
        required: true
    job-name:
        required: true

runs:
    using: "composite"
    steps:
        - name: Fetch logs
          shell: bash
          run: python ${{ github.action_path }}/fetch_logs.py -t ${{inputs.github-token}} -j ${{inputs.job-name}}
        - name: Install dependencies
          shell: bash
          run: pip install torch scikit-learn
        - name: Detection
          shell: bash
          env: ACTION_PATH = ${{ github.action_path }}
          run: python ${{ github.action_path }}/detect.py -j ${{inputs.job-name}}
