name: "Log Anomaly Detection"
inputs:
    github-token:
        required: true
    job-name:
        required: true

runs:
    using: "composite"
    steps:
        - name: Fetch logs
          shell: bash
          run: python ${{ github.action_path }}/fetch_logs.py -t ${{inputs.github-token}} -j ${{inputs.job-name}}
